### PR TITLE
network address refactoring

### PR DESCRIPTION
**Pull request by Kelindar**
Moved out the `address` package to a separate repository for reuse in message storage (upcoming). Few things here:

1. There's a breaking change, `public` alias now retrieves actual public IP address from the network interface and not an external one, added an `external` alias to retrieve the external address. Config defaults now to external address (same behavior, different name)
2. Improved acceptance test with unsubscribe, ping and disconnect.

### CODE REVIEW

**Comment by PythonLinks** [comment]
Hints of messages storage are very interesting. 

I have looked far and wide for a good message storage solution.  I have not found one.  
The problem is that disks like to write to a single file.  And lots of messages in lots of different files means lots of disk seeks.  A good message storage solution would include caching of messages in RAM, and the ability to delete messages.  

I would love to see what you are planning on building, before you devote huge amounts of energy to it.

**Comment by Kelindar** [comment]
@PythonLinks It's pretty much already built, but we're still testing it. I disagree on the caching of messages, it all depends on read patterns and I don't think caching should be handled inside a store, instead just prefetching (difference is nuanced). We've actually built something tailored specifically for SSDs.

So far what we have, in a nutshell:

1. HTTP API for appending and querying messages supporting both JSON and our Binary formats.
2. Using RAFT to replicate commit logs (batches) for message replication.
3. Disk backed message storage (LSMT), optimised for random seeks and SSDs 
4. Key space seeks are done in RAM and are very efficient.

On the feature specs, we do batches of messages and querying supports wildcard channels, last n messages, from/until time seeks as well. This is pretty much the only things our message storage needs

**Comment by clozinski** [comment]
Thank you. 

> querying supports wildcard channels, last n messages, from/until time seeks as well. 

Sounds Great.  Just exactly what is needed.   I have some idea how a relational index works.  I have no idea how you can support a wild card index.   I would imagine just checking the logs for each channel. 

So let me ask the tough questions. 
If the server crashes do you loose messages?

**Comment by Kelindar** [comment]
So far, we can tolerate server crashing without downtime, I've been testing with 3 node storage replication. Plus, even if there's downtime the actual messages are stored on disk so data should not be lost. 

That being said, there's still work to be done to make it *production ready* and this is the hard part.

**Pull request merged**
