### PR TITLE
Feature: channel-specific keys and matching, retro-compatible

### PR DESCRIPTION
**Pull request by alaingilbert**
Hi guys.

I really don't want to be a pain...
but I would like to get the contribution for this feature in the project if it doesn't bother you too much.

So this PR is basically a cherry-pick of your [other PR](https://github.com/emitter-io/emitter/pull/81).
The main difference is that I also use the byte 14 (that was unused in your PR) so we can have 23 levels depth channels.

### CODE REVIEW

**Comment by Kelindar** [comment]
@alaingilbert of course, I'll close other PR. Thanks for your contributions!

**Comment by alaingilbert** [comment]
Thank you :)

Let me know if there is anything you'd like to change.

**Comment by Kelindar** [comment]
It looks good to me, I'm going to do more manual testing and then merge it if everything is good.

**Comment by alaingilbert** [comment]
One thing I wonder is:
https://github.com/alaingilbert/emitter/commit/bed0999d44111604cc93dc28c5210462e8289056
This commit from my fork make the "topics matching" follow the MQTT spec and introduce the new `#` wildcard. This is not part of your repository.
So the `ValidateChannel` works like this wildcard exists, but it does not exists...
I am on gitter if you want to chat...

**Comment by alaingilbert** [comment]
I was able to add a retro-compatibility test:
https://github.com/alaingilbert/emitter/blob/7960b30f218b0abdac67931a86015fa69f6c96e4/security/key_test.go#L22-L32

If the bytes 12-13-14 are set to 0. It behave the same as before this feature.
The keys generated before the change are still working after it.

**Comment by Kelindar** [comment]
Tested manually as well, everything looks good. Thanks!

**Pull request merged**
